baseURL: "https://rigojr.github.io/blog/"
title: "Serre - Rigojr Blog"
theme: "PaperMod"
languageCode: "en-us"

params:
  author: "Jose Salas - @rigojr"
  homeInfoParams:
    Title: Rigojr Blog
    Content: Just for fun